server:
  port: 9002

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    open-in-view: false
keyPair:
  # I generated this just for this example project
  # openssl genrsa -out jwt.pem 2048
  # openssl rsa -in jwt.pem
  private-key: keyPair.private-key Vault placeholder
  # I generated this just for this example project
  # openssl rsa -in jwt.pem -pubout
  public-key: keyPair.public-key Vault placeholder

# cd ../vault
# vault kv put secret/authentication-service keyPair.private-key=@jwt_rsa_private.key keyPair.public-key=@jwt_rsa_public.key
