importFilePath: /2017_Gaz_ua_national.txt

security:
  oauth2:
    client:
      clientId: geography-client
      clientSecret: client-secret
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt43IFSkg+S24R0Uw9PGp
          ioGOcmFQqiivkOAC9WSTJGUVF7Joy9lXzVQtflgJ+3fgNvF1+h+5utttKF70rxM9
          bCTUYbOh5PaMU/Qo/AtmA5MaYy1iQPDsUM3v8dIqMhoqEmg1iXpHTQ6SA2vs4ZWc
          GmQFCExc+/IKZbSwa/nY+mGZapQYK5UCh/mMAlOf2RvrWcRB4lePLYNeYBvHfcSw
          niqYIIJCptoCSn9nqowYJ1GGFRYQVO1oMFMMkCA0xIskO4nxSxZCpk+3ocmHV/hk
          bJfVeSw8pZ07rFXTAVYMyd2VYqdhHL8svbT8yePYbfb4iZqoOC9r6Yd2pDLApbTi
          YQIDAQAB
          -----END PUBLIC KEY-----
server:
  port: 9003

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    password: password2
    url: jdbc:mysql://127.0.0.1:3306/geography?autoReconnect=true
    username: geography_dba
