import:
  batch-size: 999
  file-path: /2017_Gaz_ua_national.txt

security:
  oauth2:
    client:
      clientId: geography-client
      clientSecret: client-secret
    resource:
      jwt:
        keyValue: security.oauth2.resource.jwt.keyValue Vault placeholder
# cd ../vault
# vault kv put secret/geography-service security.oauth2.resource.jwt.keyValue=@jwt_rsa_public.key
server:
  port: 9003

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/geography?autoReconnect=true
    hikari:
      connection-test-query: select 1
      idle-timeout: 5000
      max-lifetime: 120000
      maximum-pool-size: 5
      minimum-idle: 5
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
