proxy:
  permitAll:
    matches: /login**/error**,/*.js,/favicon.ico,*.map,/*.css,/robots.txt

zuul:
  add-proxy-headers: true
  sensitiveHeaders: Cookie,Set-Cookie
  ignoredPatterns: /**/health/**,/**/mappings/**
  ignored-services: "*"
  routes:
    protected-site:
      path: /protected-web-site/**
      url: http://localhost:9001/protected-web-site/
    authorization-service:
      path: /authorization-server/**
      url: http://localhost:9002/authorization-service
      sensitiveHeaders: Authorization
      stripPrefix: false

security:
  oauth2:
    client:
      accessTokenUri: http://localhost:9002/oauth/token
      userAuthorizationUri: http://localhost:9002/oauth/authorize
      clientId: proxy-client
      clientSecret: client-secret
    resource:
      jwt:
        keyValue: security.oauth2.resource.jwt.keyValue Vault placeholder
# cd ../vault
# vault kv put secret/proxy-service security.oauth2.resource.jwt.keyValue=@jwt_rsa_public.key

server:
  port: 9000
  servlet:
    session:
      cookie:
        name: UISESSION
  session:
    timeout: 3600
  use-forward-headers: true


spring:
  aop:
    proxy-target-class: true
