importFilePath: /2017_Gaz_ua_national.txt

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    password: password2
    url: jdbc:mysql://127.0.0.1:3306/geography?autoReconnect=true
    username: geography_dba
