logging:
  level:
    ROOT: INFO
    org.springframework.cloud.config.server: DEBUG

server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/Development/smitchell/spring-cloud-config-vault
          search-paths: config-repo
          clone-on-start: false
